# Базовый пример использования Harold Action
# Анализирует изменения размеров бандлов в Pull Request'ах

name: Bundle Size Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-bundle:
    name: Analyze Bundle Size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Analyze bundle size changes
        uses: harold-team/harold-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-command: 'npm run build'
          build-path: 'dist'
